name: Simple CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov black flake8 mypy isort
    
    - name: Run tests
      run: |
        pytest tests/ --cov=src --cov-report=term-missing
    
    - name: Check code formatting
      run: |
        black --check src/ tests/
    
    - name: Run linting
      run: |
        flake8 src/ tests/ --max-line-length=88 --extend-ignore=E203,W503
    
    - name: Type check
      run: |
        mypy src/ --ignore-missing-imports
      continue-on-error: true
    
    - name: Check import sorting
      run: |
        isort --check-only src/ tests/
      continue-on-error: true